migration to snapshot.storage.k8s.io/v1beta1

diff --git a/hack/verify-golint b/hack/verify-golint
--- a/hack/verify-golint
+++ b/hack/verify-golint
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright 2019 The Kubernetes Authors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -12,19 +14,15 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM golang:1.14.1-stretch
+set -euo pipefail
 
-ARG DEBUG_IMAGE="disable"
+if ! which golangci-lint > /dev/null; then
+    echo "Cannot find golangci-lint. Installing golangci-lint..."
+    go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
+fi
 
-RUN apt-get -y update && \
-    if [ ${DEBUG_IMAGE} = "enable" ]; then \
-        apt-get -y --no-install-recommends install gdb=7.12-6 jq=1.5+dfsg-1.3; \
-        echo "add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py" >> /root/.gdbinit; \
-    fi && \
-    apt-get clean && \
-    rm -rf /var/lib/apt/lists/*
+echo "Running golangci-lint"
 
-WORKDIR /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver
-COPY . .
+golangci-lint run --deadline=10m --exclude "SA1019: grpc.WithDialer is deprecated"
 
-ENTRYPOINT ["./tester_entrypoint.sh"]
+echo "Congratulations! All Go source files have been linted."
